version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:4.1.8-xenial
    restart: always
    expose:
      - '27017'
    volumes:
      - db-data:/data/db
    ports:
      - '27017:27017'
volumes:
  db-data:
